apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:6.0.4
      command:
      - /bin/bash
      - -c
      env: 
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "vaxidrez"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "$VaxiDrez2025"
      ports:
        - containerPort: 27017