apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deploy
  labels:
    app: mssql-deply
    name: microservice-seguridad
spec:
  replicas: 1
  select:
    matchLabels:
      app: microservice-seguridad
      name: mssql-pod
  templates:
    metadata:
      name: mssql-pod
      labels:
        app: microservice-seguridad
        name: mssql-pod
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server
          env: 
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "$VaxiDrez2025"
          ports:
            - containerPort: 1433