name: deployando servicios net core
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Instala Net core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: "instala las dependencias"
        run: dotnet build Servicios.api.Gateway.csproj